/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cohesionforce.dis.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ReceiverPdu extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReceiverPdu\",\"namespace\":\"com.cohesionforce.dis.avro\",\"fields\":[{\"name\":\"reception_timestamp\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Time_t\",\"fields\":[{\"name\":\"sec\",\"type\":\"int\"},{\"name\":\"nanosec\",\"type\":\"int\"}]}]},{\"name\":\"source_timestamp\",\"type\":[\"null\",\"Time_t\"]},{\"name\":\"protocolVersion\",\"type\":\"int\"},{\"name\":\"exerciseID\",\"type\":\"int\"},{\"name\":\"pduType\",\"type\":\"int\"},{\"name\":\"protocolFamily\",\"type\":\"int\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"pduLength\",\"type\":\"int\"},{\"name\":\"padding\",\"type\":\"int\"},{\"name\":\"entityId\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"EntityID\",\"fields\":[{\"name\":\"site\",\"type\":\"int\"},{\"name\":\"application\",\"type\":\"int\"},{\"name\":\"entity\",\"type\":\"int\"}]}]},{\"name\":\"radioId\",\"type\":\"int\"},{\"name\":\"receiverState\",\"type\":\"int\"},{\"name\":\"padding1\",\"type\":\"int\"},{\"name\":\"receivedPoser\",\"type\":\"float\"},{\"name\":\"transmitterEntityId\",\"type\":[\"null\",\"EntityID\"]},{\"name\":\"transmitterRadioId\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public com.cohesionforce.dis.avro.Time_t reception_timestamp;
  @Deprecated public com.cohesionforce.dis.avro.Time_t source_timestamp;
  @Deprecated public int protocolVersion;
  @Deprecated public int exerciseID;
  @Deprecated public int pduType;
  @Deprecated public int protocolFamily;
  @Deprecated public long timestamp;
  @Deprecated public int pduLength;
  @Deprecated public int padding;
  @Deprecated public com.cohesionforce.dis.avro.EntityID entityId;
  @Deprecated public int radioId;
  @Deprecated public int receiverState;
  @Deprecated public int padding1;
  @Deprecated public float receivedPoser;
  @Deprecated public com.cohesionforce.dis.avro.EntityID transmitterEntityId;
  @Deprecated public int transmitterRadioId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ReceiverPdu() {}

  /**
   * All-args constructor.
   */
  public ReceiverPdu(com.cohesionforce.dis.avro.Time_t reception_timestamp, com.cohesionforce.dis.avro.Time_t source_timestamp, java.lang.Integer protocolVersion, java.lang.Integer exerciseID, java.lang.Integer pduType, java.lang.Integer protocolFamily, java.lang.Long timestamp, java.lang.Integer pduLength, java.lang.Integer padding, com.cohesionforce.dis.avro.EntityID entityId, java.lang.Integer radioId, java.lang.Integer receiverState, java.lang.Integer padding1, java.lang.Float receivedPoser, com.cohesionforce.dis.avro.EntityID transmitterEntityId, java.lang.Integer transmitterRadioId) {
    this.reception_timestamp = reception_timestamp;
    this.source_timestamp = source_timestamp;
    this.protocolVersion = protocolVersion;
    this.exerciseID = exerciseID;
    this.pduType = pduType;
    this.protocolFamily = protocolFamily;
    this.timestamp = timestamp;
    this.pduLength = pduLength;
    this.padding = padding;
    this.entityId = entityId;
    this.radioId = radioId;
    this.receiverState = receiverState;
    this.padding1 = padding1;
    this.receivedPoser = receivedPoser;
    this.transmitterEntityId = transmitterEntityId;
    this.transmitterRadioId = transmitterRadioId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return reception_timestamp;
    case 1: return source_timestamp;
    case 2: return protocolVersion;
    case 3: return exerciseID;
    case 4: return pduType;
    case 5: return protocolFamily;
    case 6: return timestamp;
    case 7: return pduLength;
    case 8: return padding;
    case 9: return entityId;
    case 10: return radioId;
    case 11: return receiverState;
    case 12: return padding1;
    case 13: return receivedPoser;
    case 14: return transmitterEntityId;
    case 15: return transmitterRadioId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: reception_timestamp = (com.cohesionforce.dis.avro.Time_t)value$; break;
    case 1: source_timestamp = (com.cohesionforce.dis.avro.Time_t)value$; break;
    case 2: protocolVersion = (java.lang.Integer)value$; break;
    case 3: exerciseID = (java.lang.Integer)value$; break;
    case 4: pduType = (java.lang.Integer)value$; break;
    case 5: protocolFamily = (java.lang.Integer)value$; break;
    case 6: timestamp = (java.lang.Long)value$; break;
    case 7: pduLength = (java.lang.Integer)value$; break;
    case 8: padding = (java.lang.Integer)value$; break;
    case 9: entityId = (com.cohesionforce.dis.avro.EntityID)value$; break;
    case 10: radioId = (java.lang.Integer)value$; break;
    case 11: receiverState = (java.lang.Integer)value$; break;
    case 12: padding1 = (java.lang.Integer)value$; break;
    case 13: receivedPoser = (java.lang.Float)value$; break;
    case 14: transmitterEntityId = (com.cohesionforce.dis.avro.EntityID)value$; break;
    case 15: transmitterRadioId = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'reception_timestamp' field.
   */
  public com.cohesionforce.dis.avro.Time_t getReceptionTimestamp() {
    return reception_timestamp;
  }

  /**
   * Sets the value of the 'reception_timestamp' field.
   * @param value the value to set.
   */
  public void setReceptionTimestamp(com.cohesionforce.dis.avro.Time_t value) {
    this.reception_timestamp = value;
  }

  /**
   * Gets the value of the 'source_timestamp' field.
   */
  public com.cohesionforce.dis.avro.Time_t getSourceTimestamp() {
    return source_timestamp;
  }

  /**
   * Sets the value of the 'source_timestamp' field.
   * @param value the value to set.
   */
  public void setSourceTimestamp(com.cohesionforce.dis.avro.Time_t value) {
    this.source_timestamp = value;
  }

  /**
   * Gets the value of the 'protocolVersion' field.
   */
  public java.lang.Integer getProtocolVersion() {
    return protocolVersion;
  }

  /**
   * Sets the value of the 'protocolVersion' field.
   * @param value the value to set.
   */
  public void setProtocolVersion(java.lang.Integer value) {
    this.protocolVersion = value;
  }

  /**
   * Gets the value of the 'exerciseID' field.
   */
  public java.lang.Integer getExerciseID() {
    return exerciseID;
  }

  /**
   * Sets the value of the 'exerciseID' field.
   * @param value the value to set.
   */
  public void setExerciseID(java.lang.Integer value) {
    this.exerciseID = value;
  }

  /**
   * Gets the value of the 'pduType' field.
   */
  public java.lang.Integer getPduType() {
    return pduType;
  }

  /**
   * Sets the value of the 'pduType' field.
   * @param value the value to set.
   */
  public void setPduType(java.lang.Integer value) {
    this.pduType = value;
  }

  /**
   * Gets the value of the 'protocolFamily' field.
   */
  public java.lang.Integer getProtocolFamily() {
    return protocolFamily;
  }

  /**
   * Sets the value of the 'protocolFamily' field.
   * @param value the value to set.
   */
  public void setProtocolFamily(java.lang.Integer value) {
    this.protocolFamily = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'pduLength' field.
   */
  public java.lang.Integer getPduLength() {
    return pduLength;
  }

  /**
   * Sets the value of the 'pduLength' field.
   * @param value the value to set.
   */
  public void setPduLength(java.lang.Integer value) {
    this.pduLength = value;
  }

  /**
   * Gets the value of the 'padding' field.
   */
  public java.lang.Integer getPadding() {
    return padding;
  }

  /**
   * Sets the value of the 'padding' field.
   * @param value the value to set.
   */
  public void setPadding(java.lang.Integer value) {
    this.padding = value;
  }

  /**
   * Gets the value of the 'entityId' field.
   */
  public com.cohesionforce.dis.avro.EntityID getEntityId() {
    return entityId;
  }

  /**
   * Sets the value of the 'entityId' field.
   * @param value the value to set.
   */
  public void setEntityId(com.cohesionforce.dis.avro.EntityID value) {
    this.entityId = value;
  }

  /**
   * Gets the value of the 'radioId' field.
   */
  public java.lang.Integer getRadioId() {
    return radioId;
  }

  /**
   * Sets the value of the 'radioId' field.
   * @param value the value to set.
   */
  public void setRadioId(java.lang.Integer value) {
    this.radioId = value;
  }

  /**
   * Gets the value of the 'receiverState' field.
   */
  public java.lang.Integer getReceiverState() {
    return receiverState;
  }

  /**
   * Sets the value of the 'receiverState' field.
   * @param value the value to set.
   */
  public void setReceiverState(java.lang.Integer value) {
    this.receiverState = value;
  }

  /**
   * Gets the value of the 'padding1' field.
   */
  public java.lang.Integer getPadding1() {
    return padding1;
  }

  /**
   * Sets the value of the 'padding1' field.
   * @param value the value to set.
   */
  public void setPadding1(java.lang.Integer value) {
    this.padding1 = value;
  }

  /**
   * Gets the value of the 'receivedPoser' field.
   */
  public java.lang.Float getReceivedPoser() {
    return receivedPoser;
  }

  /**
   * Sets the value of the 'receivedPoser' field.
   * @param value the value to set.
   */
  public void setReceivedPoser(java.lang.Float value) {
    this.receivedPoser = value;
  }

  /**
   * Gets the value of the 'transmitterEntityId' field.
   */
  public com.cohesionforce.dis.avro.EntityID getTransmitterEntityId() {
    return transmitterEntityId;
  }

  /**
   * Sets the value of the 'transmitterEntityId' field.
   * @param value the value to set.
   */
  public void setTransmitterEntityId(com.cohesionforce.dis.avro.EntityID value) {
    this.transmitterEntityId = value;
  }

  /**
   * Gets the value of the 'transmitterRadioId' field.
   */
  public java.lang.Integer getTransmitterRadioId() {
    return transmitterRadioId;
  }

  /**
   * Sets the value of the 'transmitterRadioId' field.
   * @param value the value to set.
   */
  public void setTransmitterRadioId(java.lang.Integer value) {
    this.transmitterRadioId = value;
  }

  /** Creates a new ReceiverPdu RecordBuilder */
  public static com.cohesionforce.dis.avro.ReceiverPdu.Builder newBuilder() {
    return new com.cohesionforce.dis.avro.ReceiverPdu.Builder();
  }
  
  /** Creates a new ReceiverPdu RecordBuilder by copying an existing Builder */
  public static com.cohesionforce.dis.avro.ReceiverPdu.Builder newBuilder(com.cohesionforce.dis.avro.ReceiverPdu.Builder other) {
    return new com.cohesionforce.dis.avro.ReceiverPdu.Builder(other);
  }
  
  /** Creates a new ReceiverPdu RecordBuilder by copying an existing ReceiverPdu instance */
  public static com.cohesionforce.dis.avro.ReceiverPdu.Builder newBuilder(com.cohesionforce.dis.avro.ReceiverPdu other) {
    return new com.cohesionforce.dis.avro.ReceiverPdu.Builder(other);
  }
  
  /**
   * RecordBuilder for ReceiverPdu instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReceiverPdu>
    implements org.apache.avro.data.RecordBuilder<ReceiverPdu> {

    private com.cohesionforce.dis.avro.Time_t reception_timestamp;
    private com.cohesionforce.dis.avro.Time_t source_timestamp;
    private int protocolVersion;
    private int exerciseID;
    private int pduType;
    private int protocolFamily;
    private long timestamp;
    private int pduLength;
    private int padding;
    private com.cohesionforce.dis.avro.EntityID entityId;
    private int radioId;
    private int receiverState;
    private int padding1;
    private float receivedPoser;
    private com.cohesionforce.dis.avro.EntityID transmitterEntityId;
    private int transmitterRadioId;

    /** Creates a new Builder */
    private Builder() {
      super(com.cohesionforce.dis.avro.ReceiverPdu.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cohesionforce.dis.avro.ReceiverPdu.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.reception_timestamp)) {
        this.reception_timestamp = data().deepCopy(fields()[0].schema(), other.reception_timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.source_timestamp)) {
        this.source_timestamp = data().deepCopy(fields()[1].schema(), other.source_timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.protocolVersion)) {
        this.protocolVersion = data().deepCopy(fields()[2].schema(), other.protocolVersion);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.exerciseID)) {
        this.exerciseID = data().deepCopy(fields()[3].schema(), other.exerciseID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pduType)) {
        this.pduType = data().deepCopy(fields()[4].schema(), other.pduType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.protocolFamily)) {
        this.protocolFamily = data().deepCopy(fields()[5].schema(), other.protocolFamily);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.pduLength)) {
        this.pduLength = data().deepCopy(fields()[7].schema(), other.pduLength);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.padding)) {
        this.padding = data().deepCopy(fields()[8].schema(), other.padding);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.entityId)) {
        this.entityId = data().deepCopy(fields()[9].schema(), other.entityId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.radioId)) {
        this.radioId = data().deepCopy(fields()[10].schema(), other.radioId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.receiverState)) {
        this.receiverState = data().deepCopy(fields()[11].schema(), other.receiverState);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.padding1)) {
        this.padding1 = data().deepCopy(fields()[12].schema(), other.padding1);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.receivedPoser)) {
        this.receivedPoser = data().deepCopy(fields()[13].schema(), other.receivedPoser);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.transmitterEntityId)) {
        this.transmitterEntityId = data().deepCopy(fields()[14].schema(), other.transmitterEntityId);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.transmitterRadioId)) {
        this.transmitterRadioId = data().deepCopy(fields()[15].schema(), other.transmitterRadioId);
        fieldSetFlags()[15] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ReceiverPdu instance */
    private Builder(com.cohesionforce.dis.avro.ReceiverPdu other) {
            super(com.cohesionforce.dis.avro.ReceiverPdu.SCHEMA$);
      if (isValidValue(fields()[0], other.reception_timestamp)) {
        this.reception_timestamp = data().deepCopy(fields()[0].schema(), other.reception_timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.source_timestamp)) {
        this.source_timestamp = data().deepCopy(fields()[1].schema(), other.source_timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.protocolVersion)) {
        this.protocolVersion = data().deepCopy(fields()[2].schema(), other.protocolVersion);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.exerciseID)) {
        this.exerciseID = data().deepCopy(fields()[3].schema(), other.exerciseID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pduType)) {
        this.pduType = data().deepCopy(fields()[4].schema(), other.pduType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.protocolFamily)) {
        this.protocolFamily = data().deepCopy(fields()[5].schema(), other.protocolFamily);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.pduLength)) {
        this.pduLength = data().deepCopy(fields()[7].schema(), other.pduLength);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.padding)) {
        this.padding = data().deepCopy(fields()[8].schema(), other.padding);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.entityId)) {
        this.entityId = data().deepCopy(fields()[9].schema(), other.entityId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.radioId)) {
        this.radioId = data().deepCopy(fields()[10].schema(), other.radioId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.receiverState)) {
        this.receiverState = data().deepCopy(fields()[11].schema(), other.receiverState);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.padding1)) {
        this.padding1 = data().deepCopy(fields()[12].schema(), other.padding1);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.receivedPoser)) {
        this.receivedPoser = data().deepCopy(fields()[13].schema(), other.receivedPoser);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.transmitterEntityId)) {
        this.transmitterEntityId = data().deepCopy(fields()[14].schema(), other.transmitterEntityId);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.transmitterRadioId)) {
        this.transmitterRadioId = data().deepCopy(fields()[15].schema(), other.transmitterRadioId);
        fieldSetFlags()[15] = true;
      }
    }

    /** Gets the value of the 'reception_timestamp' field */
    public com.cohesionforce.dis.avro.Time_t getReceptionTimestamp() {
      return reception_timestamp;
    }
    
    /** Sets the value of the 'reception_timestamp' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setReceptionTimestamp(com.cohesionforce.dis.avro.Time_t value) {
      validate(fields()[0], value);
      this.reception_timestamp = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'reception_timestamp' field has been set */
    public boolean hasReceptionTimestamp() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'reception_timestamp' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearReceptionTimestamp() {
      reception_timestamp = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'source_timestamp' field */
    public com.cohesionforce.dis.avro.Time_t getSourceTimestamp() {
      return source_timestamp;
    }
    
    /** Sets the value of the 'source_timestamp' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setSourceTimestamp(com.cohesionforce.dis.avro.Time_t value) {
      validate(fields()[1], value);
      this.source_timestamp = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'source_timestamp' field has been set */
    public boolean hasSourceTimestamp() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'source_timestamp' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearSourceTimestamp() {
      source_timestamp = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'protocolVersion' field */
    public java.lang.Integer getProtocolVersion() {
      return protocolVersion;
    }
    
    /** Sets the value of the 'protocolVersion' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setProtocolVersion(int value) {
      validate(fields()[2], value);
      this.protocolVersion = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'protocolVersion' field has been set */
    public boolean hasProtocolVersion() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'protocolVersion' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearProtocolVersion() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'exerciseID' field */
    public java.lang.Integer getExerciseID() {
      return exerciseID;
    }
    
    /** Sets the value of the 'exerciseID' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setExerciseID(int value) {
      validate(fields()[3], value);
      this.exerciseID = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'exerciseID' field has been set */
    public boolean hasExerciseID() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'exerciseID' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearExerciseID() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'pduType' field */
    public java.lang.Integer getPduType() {
      return pduType;
    }
    
    /** Sets the value of the 'pduType' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setPduType(int value) {
      validate(fields()[4], value);
      this.pduType = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'pduType' field has been set */
    public boolean hasPduType() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'pduType' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearPduType() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'protocolFamily' field */
    public java.lang.Integer getProtocolFamily() {
      return protocolFamily;
    }
    
    /** Sets the value of the 'protocolFamily' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setProtocolFamily(int value) {
      validate(fields()[5], value);
      this.protocolFamily = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'protocolFamily' field has been set */
    public boolean hasProtocolFamily() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'protocolFamily' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearProtocolFamily() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setTimestamp(long value) {
      validate(fields()[6], value);
      this.timestamp = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'timestamp' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'pduLength' field */
    public java.lang.Integer getPduLength() {
      return pduLength;
    }
    
    /** Sets the value of the 'pduLength' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setPduLength(int value) {
      validate(fields()[7], value);
      this.pduLength = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'pduLength' field has been set */
    public boolean hasPduLength() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'pduLength' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearPduLength() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'padding' field */
    public java.lang.Integer getPadding() {
      return padding;
    }
    
    /** Sets the value of the 'padding' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setPadding(int value) {
      validate(fields()[8], value);
      this.padding = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'padding' field has been set */
    public boolean hasPadding() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'padding' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearPadding() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'entityId' field */
    public com.cohesionforce.dis.avro.EntityID getEntityId() {
      return entityId;
    }
    
    /** Sets the value of the 'entityId' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setEntityId(com.cohesionforce.dis.avro.EntityID value) {
      validate(fields()[9], value);
      this.entityId = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'entityId' field has been set */
    public boolean hasEntityId() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'entityId' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearEntityId() {
      entityId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'radioId' field */
    public java.lang.Integer getRadioId() {
      return radioId;
    }
    
    /** Sets the value of the 'radioId' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setRadioId(int value) {
      validate(fields()[10], value);
      this.radioId = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'radioId' field has been set */
    public boolean hasRadioId() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'radioId' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearRadioId() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'receiverState' field */
    public java.lang.Integer getReceiverState() {
      return receiverState;
    }
    
    /** Sets the value of the 'receiverState' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setReceiverState(int value) {
      validate(fields()[11], value);
      this.receiverState = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'receiverState' field has been set */
    public boolean hasReceiverState() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'receiverState' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearReceiverState() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'padding1' field */
    public java.lang.Integer getPadding1() {
      return padding1;
    }
    
    /** Sets the value of the 'padding1' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setPadding1(int value) {
      validate(fields()[12], value);
      this.padding1 = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'padding1' field has been set */
    public boolean hasPadding1() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'padding1' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearPadding1() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'receivedPoser' field */
    public java.lang.Float getReceivedPoser() {
      return receivedPoser;
    }
    
    /** Sets the value of the 'receivedPoser' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setReceivedPoser(float value) {
      validate(fields()[13], value);
      this.receivedPoser = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'receivedPoser' field has been set */
    public boolean hasReceivedPoser() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'receivedPoser' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearReceivedPoser() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'transmitterEntityId' field */
    public com.cohesionforce.dis.avro.EntityID getTransmitterEntityId() {
      return transmitterEntityId;
    }
    
    /** Sets the value of the 'transmitterEntityId' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setTransmitterEntityId(com.cohesionforce.dis.avro.EntityID value) {
      validate(fields()[14], value);
      this.transmitterEntityId = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'transmitterEntityId' field has been set */
    public boolean hasTransmitterEntityId() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'transmitterEntityId' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearTransmitterEntityId() {
      transmitterEntityId = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'transmitterRadioId' field */
    public java.lang.Integer getTransmitterRadioId() {
      return transmitterRadioId;
    }
    
    /** Sets the value of the 'transmitterRadioId' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder setTransmitterRadioId(int value) {
      validate(fields()[15], value);
      this.transmitterRadioId = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'transmitterRadioId' field has been set */
    public boolean hasTransmitterRadioId() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'transmitterRadioId' field */
    public com.cohesionforce.dis.avro.ReceiverPdu.Builder clearTransmitterRadioId() {
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    public ReceiverPdu build() {
      try {
        ReceiverPdu record = new ReceiverPdu();
        record.reception_timestamp = fieldSetFlags()[0] ? this.reception_timestamp : (com.cohesionforce.dis.avro.Time_t) defaultValue(fields()[0]);
        record.source_timestamp = fieldSetFlags()[1] ? this.source_timestamp : (com.cohesionforce.dis.avro.Time_t) defaultValue(fields()[1]);
        record.protocolVersion = fieldSetFlags()[2] ? this.protocolVersion : (java.lang.Integer) defaultValue(fields()[2]);
        record.exerciseID = fieldSetFlags()[3] ? this.exerciseID : (java.lang.Integer) defaultValue(fields()[3]);
        record.pduType = fieldSetFlags()[4] ? this.pduType : (java.lang.Integer) defaultValue(fields()[4]);
        record.protocolFamily = fieldSetFlags()[5] ? this.protocolFamily : (java.lang.Integer) defaultValue(fields()[5]);
        record.timestamp = fieldSetFlags()[6] ? this.timestamp : (java.lang.Long) defaultValue(fields()[6]);
        record.pduLength = fieldSetFlags()[7] ? this.pduLength : (java.lang.Integer) defaultValue(fields()[7]);
        record.padding = fieldSetFlags()[8] ? this.padding : (java.lang.Integer) defaultValue(fields()[8]);
        record.entityId = fieldSetFlags()[9] ? this.entityId : (com.cohesionforce.dis.avro.EntityID) defaultValue(fields()[9]);
        record.radioId = fieldSetFlags()[10] ? this.radioId : (java.lang.Integer) defaultValue(fields()[10]);
        record.receiverState = fieldSetFlags()[11] ? this.receiverState : (java.lang.Integer) defaultValue(fields()[11]);
        record.padding1 = fieldSetFlags()[12] ? this.padding1 : (java.lang.Integer) defaultValue(fields()[12]);
        record.receivedPoser = fieldSetFlags()[13] ? this.receivedPoser : (java.lang.Float) defaultValue(fields()[13]);
        record.transmitterEntityId = fieldSetFlags()[14] ? this.transmitterEntityId : (com.cohesionforce.dis.avro.EntityID) defaultValue(fields()[14]);
        record.transmitterRadioId = fieldSetFlags()[15] ? this.transmitterRadioId : (java.lang.Integer) defaultValue(fields()[15]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
